import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hostel management system</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h2 className="text-center mt-5">Hello Full Stack Force</h2>
      </main>
    </>
  );
}
